/* eslint-disable */
// @ts-nocheck
// biome-ignore lint: disable
// oxlint-disable
// ------
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399

export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    BAlert: typeof import('bootstrap-vue-next/components/BAlert')['BAlert']
    BBadge: typeof import('bootstrap-vue-next/components/BBadge')['BBadge']
    BButton: typeof import('bootstrap-vue-next/components/BButton')['BButton']
    BCard: typeof import('bootstrap-vue-next/components/BCard')['BCard']
    BCardBody: typeof import('bootstrap-vue-next/components/BCard')['BCardBody']
    BCol: typeof import('bootstrap-vue-next/components/BContainer')['BCol']
    BForm: typeof import('bootstrap-vue-next/components/BForm')['BForm']
    BFormGroup: typeof import('bootstrap-vue-next/components/BFormGroup')['BFormGroup']
    BFormInput: typeof import('bootstrap-vue-next/components/BFormInput')['BFormInput']
    BFormText: typeof import('bootstrap-vue-next/components/BForm')['BFormText']
    BFormTextarea: typeof import('bootstrap-vue-next/components/BFormTextarea')['BFormTextarea']
    BInputGroup: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroup']
    BInputGroupText: typeof import('bootstrap-vue-next/components/BInputGroup')['BInputGroupText']
    BModal: typeof import('bootstrap-vue-next/components/BModal')['BModal']
    BPagination: typeof import('bootstrap-vue-next/components/BPagination')['BPagination']
    BRow: typeof import('bootstrap-vue-next/components/BContainer')['BRow']
    BSpinner: typeof import('bootstrap-vue-next/components/BSpinner')['BSpinner']
    BTable: typeof import('bootstrap-vue-next/components/BTable')['BTable']
    GamerSidebar: typeof import('./src/components/GamerSidebar.vue')['default']
    ImagePreview: typeof import('./src/components/ImagePreview.vue')['default']
    Preloader: typeof import('./src/components/Preloader.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
  }
  export interface GlobalDirectives {
    vBTooltip: typeof import('bootstrap-vue-next/directives/BTooltip')['vBTooltip']
  }
}
